//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIPOL_UF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DIPOL_UF.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulation cycle settings:.
        /// </summary>
        public static string AcquisitionSettings_AccumulationCycle {
            get {
                return ResourceManager.GetString("AcquisitionSettings_AccumulationCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Camera or camera Acquisition Mode does not support either of Accumulation or Kinetic cycles..
        /// </summary>
        public static string AcquisitionSettings_AcquisitionModeDoesNotSupportCycles {
            get {
                return ResourceManager.GetString("AcquisitionSettings_AcquisitionModeDoesNotSupportCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to apply settings.
        /// </summary>
        public static string AcquisitionSettings_ApplicationFailed {
            get {
                return ResourceManager.GetString("AcquisitionSettings_ApplicationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error happened while applying acquisition settings: &quot;{0}&quot;.
        ///The following settings produced this error:
        ///{1}.
        /// </summary>
        public static string AcquisitionSettings_ApplicationFailed_Message {
            get {
                return ResourceManager.GetString("AcquisitionSettings_ApplicationFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unrecoverable error happened while applying acquisition settings, which indicates the program is in a faulty state. The error message is:
        ///{0}.
        /// </summary>
        public static string AcquisitionSettings_ApplicationFailedUnrecoverable_Message {
            get {
                return ResourceManager.GetString("AcquisitionSettings_ApplicationFailedUnrecoverable_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of cycles.
        /// </summary>
        public static string AcquisitionSettings_CycleNumber {
            get {
                return ResourceManager.GetString("AcquisitionSettings_CycleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycles.
        /// </summary>
        public static string AcquisitionSettings_Cycles {
            get {
                return ResourceManager.GetString("AcquisitionSettings_Cycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle time (s).
        /// </summary>
        public static string AcquisitionSettings_CycleTime {
            get {
                return ResourceManager.GetString("AcquisitionSettings_CycleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading acquisition settings to {0}:
        ///{1}.
        /// </summary>
        public static string AcquisitionSettings_DeserializationFailed_Message {
            get {
                return ResourceManager.GetString("AcquisitionSettings_DeserializationFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load file.
        /// </summary>
        public static string AcquisitionSettings_DeserializationFailed_Title {
            get {
                return ResourceManager.GetString("AcquisitionSettings_DeserializationFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detector size (H x V):.
        /// </summary>
        public static string AcquisitionSettings_DetectorSize {
            get {
                return ResourceManager.GetString("AcquisitionSettings_DetectorSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} x {1}.
        /// </summary>
        public static string AcquisitionSettings_DetectorSize_Format {
            get {
                return ResourceManager.GetString("AcquisitionSettings_DetectorSize_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load current acquisition settings.
        /// </summary>
        public static string AcquisitionSettings_Dialog_Load_Title {
            get {
                return ResourceManager.GetString("AcquisitionSettings_Dialog_Load_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current acquisition settings.
        /// </summary>
        public static string AcquisitionSettings_Dialog_Save_Title {
            get {
                return ResourceManager.GetString("AcquisitionSettings_Dialog_Save_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size.
        /// </summary>
        public static string AcquisitionSettings_ImageSize {
            get {
                return ResourceManager.GetString("AcquisitionSettings_ImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinetic cycle settings:.
        /// </summary>
        public static string AcquisitionSettings_KineticCycle {
            get {
                return ResourceManager.GetString("AcquisitionSettings_KineticCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving acquisition settings to {0}:
        ///{1}.
        /// </summary>
        public static string AcquisitionSettings_SerializationFailed_Message {
            get {
                return ResourceManager.GetString("AcquisitionSettings_SerializationFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save file.
        /// </summary>
        public static string AcquisitionSettings_SerializationFailed_Title {
            get {
                return ResourceManager.GetString("AcquisitionSettings_SerializationFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string AcquisitionSettings_Settings {
            get {
                return ResourceManager.GetString("AcquisitionSettings_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string AcquisitionSettings_UnknownSetting {
            get {
                return ResourceManager.GetString("AcquisitionSettings_UnknownSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up acquisition process.
        /// </summary>
        public static string AcquisitionSettings_WindowName {
            get {
                return ResourceManager.GetString("AcquisitionSettings_WindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}, {1}].
        /// </summary>
        public static string AcquisitionSetttings_AvailableGainFormat {
            get {
                return ResourceManager.GetString("AcquisitionSetttings_AvailableGainFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dipol-UF.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Cameras.
        /// </summary>
        public static string AvailableCameras {
            get {
                return ResourceManager.GetString("AvailableCameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquired local camera {0}..
        /// </summary>
        public static string AvailableCameras_AcquiredLocalCamera {
            get {
                return ResourceManager.GetString("AvailableCameras_AcquiredLocalCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquired remote camera {0}..
        /// </summary>
        public static string AvailableCameras_AcquiredRemoteCamera {
            get {
                return ResourceManager.GetString("AvailableCameras_AcquiredRemoteCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera resource is unavailable..
        /// </summary>
        public static string AvailableCameras_CameraIsUnavailable {
            get {
                return ResourceManager.GetString("AvailableCameras_CameraIsUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking connections....
        /// </summary>
        public static string AvailableCameras_CheckingConnection_BarTitle {
            get {
                return ResourceManager.GetString("AvailableCameras_CheckingConnection_BarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        public static string AvailableCameras_Found {
            get {
                return ResourceManager.GetString("AvailableCameras_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cameras available. Check connections and try again..
        /// </summary>
        public static string AvailableCameras_NoNewCameras {
            get {
                return ResourceManager.GetString("AvailableCameras_NoNewCameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polarimetric regime has changed.
        /// </summary>
        public static string CalciteWarning_Caption {
            get {
                return ResourceManager.GetString("CalciteWarning_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The polarimetric regime has changed from &apos;{0}&apos; to &apos;{1}&apos;. Make sure the correct plate is used (HWP for linear, QWP for circular)..
        /// </summary>
        public static string CalciteWarning_Message {
            get {
                return ResourceManager.GetString("CalciteWarning_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string CameraProperties_Alias {
            get {
                return ResourceManager.GetString("CameraProperties_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Model.
        /// </summary>
        public static string CameraProperties_CamModel {
            get {
                return ResourceManager.GetString("CameraProperties_CamModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Version.
        /// </summary>
        public static string CameraProperties_HardwareVers {
            get {
                return ResourceManager.GetString("CameraProperties_HardwareVers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string CameraProperties_Property {
            get {
                return ResourceManager.GetString("CameraProperties_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string CameraProperties_SerialNumber {
            get {
                return ResourceManager.GetString("CameraProperties_SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Version.
        /// </summary>
        public static string CameraProperties_SoftwareVers {
            get {
                return ResourceManager.GetString("CameraProperties_SoftwareVers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string CameraProperties_UnknownValue {
            get {
                return ResourceManager.GetString("CameraProperties_UnknownValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string CameraProperties_Value {
            get {
                return ResourceManager.GetString("CameraProperties_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition.
        /// </summary>
        public static string CameraTab_Acquisition {
            get {
                return ResourceManager.GetString("CameraTab_Acquisition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acq. Settings.
        /// </summary>
        public static string CameraTab_AcquisitionSettings {
            get {
                return ResourceManager.GetString("CameraTab_AcquisitionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autosave.
        /// </summary>
        public static string CameraTab_Autosave_Checkbox {
            get {
                return ResourceManager.GetString("CameraTab_Autosave_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooler.
        /// </summary>
        public static string CameraTab_Cooler {
            get {
                return ResourceManager.GetString("CameraTab_Cooler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start cooling.
        /// </summary>
        public static string CameraTab_Cooler_Start {
            get {
                return ResourceManager.GetString("CameraTab_Cooler_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop cooling.
        /// </summary>
        public static string CameraTab_Cooler_Stop {
            get {
                return ResourceManager.GetString("CameraTab_Cooler_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act. time (s):.
        /// </summary>
        public static string CameraTab_EstimatedTime {
            get {
                return ResourceManager.GetString("CameraTab_EstimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan.
        /// </summary>
        public static string CameraTab_Fan {
            get {
                return ResourceManager.GetString("CameraTab_Fan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Imaging.
        /// </summary>
        public static string CameraTab_Imaging_Start {
            get {
                return ResourceManager.GetString("CameraTab_Imaging_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start all.
        /// </summary>
        public static string CameraTab_Imaging_StartAll {
            get {
                return ResourceManager.GetString("CameraTab_Imaging_StartAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Imaging.
        /// </summary>
        public static string CameraTab_Imaging_Stop {
            get {
                return ResourceManager.GetString("CameraTab_Imaging_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop all.
        /// </summary>
        public static string CameraTab_Imaging_StopAll {
            get {
                return ResourceManager.GetString("CameraTab_Imaging_StopAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Cycle.
        /// </summary>
        public static string CameraTab_Job_Start {
            get {
                return ResourceManager.GetString("CameraTab_Job_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Cycle.
        /// </summary>
        public static string CameraTab_Job_Stop {
            get {
                return ResourceManager.GetString("CameraTab_Job_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:d3}/{1:d3}.
        /// </summary>
        public static string CameraTab_JobProgressFormat {
            get {
                return ResourceManager.GetString("CameraTab_JobProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Settings.
        /// </summary>
        public static string CameraTab_JobSettings {
            get {
                return ResourceManager.GetString("CameraTab_JobSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last image: {0}.
        /// </summary>
        public static string CameraTab_LastSavedFile {
            get {
                return ResourceManager.GetString("CameraTab_LastSavedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Current.
        /// </summary>
        public static string CameraTab_SaveSingleButton {
            get {
                return ResourceManager.GetString("CameraTab_SaveSingleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        public static string CameraTab_Shutter_External {
            get {
                return ResourceManager.GetString("CameraTab_Shutter_External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        public static string CameraTab_Shutter_Internal {
            get {
                return ResourceManager.GetString("CameraTab_Shutter_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,6}°.
        /// </summary>
        public static string CameraTab_StepMotorAngleFormat {
            get {
                return ResourceManager.GetString("CameraTab_StepMotorAngleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of repeats:.
        /// </summary>
        public static string CycleConfigView_NRepeats {
            get {
                return ResourceManager.GetString("CycleConfigView_NRepeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure next cycle.
        /// </summary>
        public static string CycleConfigView_WindowTitle {
            get {
                return ResourceManager.GetString("CycleConfigView_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperture settings.
        /// </summary>
        public static string DipolImagePresenter_ApertureControlGroup {
            get {
                return ResourceManager.GetString("DipolImagePresenter_ApertureControlGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,6:000}:{1,-6:000}.
        /// </summary>
        public static string DipolImagePresenter_CenterPixelFormat {
            get {
                return ResourceManager.GetString("DipolImagePresenter_CenterPixelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gap.
        /// </summary>
        public static string DipolImagePresenter_Geometry_Gap {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Geometry_Gap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line thickness.
        /// </summary>
        public static string DipolImagePresenter_Geometry_Thickness {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Geometry_Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string DipolImagePresenter_Geometry_Type {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Geometry_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulus.
        /// </summary>
        public static string DipolImagePresenter_Statistics_Annulus {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_Annulus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperture.
        /// </summary>
        public static string DipolImagePresenter_Statistics_Aperture {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_Aperture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string DipolImagePresenter_Statistics_Average {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center pixel.
        /// </summary>
        public static string DipolImagePresenter_Statistics_CenterPixel {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_CenterPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string DipolImagePresenter_Statistics_CenterPosition {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_CenterPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string DipolImagePresenter_Statistics_CenterValue {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_CenterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        public static string DipolImagePresenter_Statistics_Intensity {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_Intensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string DipolImagePresenter_Statistics_Maximum {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median.
        /// </summary>
        public static string DipolImagePresenter_Statistics_Median {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_Median", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string DipolImagePresenter_Statistics_Minimum {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNR.
        /// </summary>
        public static string DipolImagePresenter_Statistics_SignalToNoise {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_SignalToNoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD.
        /// </summary>
        public static string DipolImagePresenter_Statistics_StandardDev {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_StandardDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full width at half maximum.
        /// </summary>
        public static string FWHM_Caption {
            get {
                return ResourceManager.GetString("FWHM_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center:	{0:F2}, {1:F2}.
        /// </summary>
        public static string FWHM_Center {
            get {
                return ResourceManager.GetString("FWHM_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FWHM:	{0:G5} x {1:G5}.
        /// </summary>
        public static string FWHM_Value {
            get {
                return ResourceManager.GetString("FWHM_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string General_Abort {
            get {
                return ResourceManager.GetString("General_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string General_Browse {
            get {
                return ResourceManager.GetString("General_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string General_Cancel {
            get {
                return ResourceManager.GetString("General_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string General_Color {
            get {
                return ResourceManager.GetString("General_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string General_Connect {
            get {
                return ResourceManager.GetString("General_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect All.
        /// </summary>
        public static string General_ConnectAll {
            get {
                return ResourceManager.GetString("General_ConnectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string General_CreateNew {
            get {
                return ResourceManager.GetString("General_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string General_Disconnect {
            get {
                return ResourceManager.GetString("General_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G6.
        /// </summary>
        public static string General_ExposureFloatFormat {
            get {
                return ResourceManager.GetString("General_ExposureFloatFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string General_FanMode_Full {
            get {
                return ResourceManager.GetString("General_FanMode_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string General_FanMode_Low {
            get {
                return ResourceManager.GetString("General_FanMode_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string General_FanMode_Off {
            get {
                return ResourceManager.GetString("General_FanMode_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +0.00;-0.00;0.00.
        /// </summary>
        public static string General_FloatTempFormat {
            get {
                return ResourceManager.GetString("General_FloatTempFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photometry.
        /// </summary>
        public static string General_InstrumentRegime_Photometer {
            get {
                return ResourceManager.GetString("General_InstrumentRegime_Photometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polarimetry.
        /// </summary>
        public static string General_InstrumentRegime_Polarimeter {
            get {
                return ResourceManager.GetString("General_InstrumentRegime_Polarimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string General_InstrumentRegime_Unknown {
            get {
                return ResourceManager.GetString("General_InstrumentRegime_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string General_IntegerFormat {
            get {
                return ResourceManager.GetString("General_IntegerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} is invalid..
        /// </summary>
        public static string General_InvalidArgument {
            get {
                return ResourceManager.GetString("General_InvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string General_Load {
            get {
                return ResourceManager.GetString("General_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string General_LocalHostName {
            get {
                return ResourceManager.GetString("General_LocalHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation [{0}] is not supported..
        /// </summary>
        public static string General_OperationNotSupported {
            get {
                return ResourceManager.GetString("General_OperationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string General_Save {
            get {
                return ResourceManager.GetString("General_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has happened. This indicates a likely unrecoverable error in the software. Consider reporting it..
        /// </summary>
        public static string General_ShouldNotHappen {
            get {
                return ResourceManager.GetString("General_ShouldNotHappen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string General_Submit {
            get {
                return ResourceManager.GetString("General_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G2.
        /// </summary>
        public static string General_TemperatureFloatFormat {
            get {
                return ResourceManager.GetString("General_TemperatureFloatFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drifting.
        /// </summary>
        public static string General_TemperatureStatus_Drift {
            get {
                return ResourceManager.GetString("General_TemperatureStatus_Drift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not reached.
        /// </summary>
        public static string General_TemperatureStatus_NotReached {
            get {
                return ResourceManager.GetString("General_TemperatureStatus_NotReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not stabilized.
        /// </summary>
        public static string General_TemperatureStatus_NotStabilized {
            get {
                return ResourceManager.GetString("General_TemperatureStatus_NotStabilized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string General_TemperatureStatus_Off {
            get {
                return ResourceManager.GetString("General_TemperatureStatus_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stabilized.
        /// </summary>
        public static string General_TemperatureStatus_Stabilized {
            get {
                return ResourceManager.GetString("General_TemperatureStatus_Stabilized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string JobManager_AcquisitionJobName {
            get {
                return ResourceManager.GetString("JobManager_AcquisitionJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bias.
        /// </summary>
        public static string JobManager_BiasJobName {
            get {
                return ResourceManager.GetString("JobManager_BiasJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string JobManager_DarkJobName {
            get {
                return ResourceManager.GetString("JobManager_DarkJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load job description.
        /// </summary>
        public static string JobManager_Error_Caption {
            get {
                return ResourceManager.GetString("JobManager_Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested file was not found:
        ///{0}.
        /// </summary>
        public static string JobManager_Error_FileNotFound {
            get {
                return ResourceManager.GetString("JobManager_Error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job configuration failed:
        ///{0}.
        /// </summary>
        public static string JobManager_Error_InvalidOp {
            get {
                return ResourceManager.GetString("JobManager_Error_InvalidOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An undefined error happened:
        ///{0}.
        /// </summary>
        public static string JobManager_Error_Other {
            get {
                return ResourceManager.GetString("JobManager_Error_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while setting up a new job.
        /// </summary>
        public static string JobManager_GenericError_Header {
            get {
                return ResourceManager.GetString("JobManager_GenericError_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dipol-UF is in invalid state.
        /// </summary>
        public static string JobManager_InvalidState_Header {
            get {
                return ResourceManager.GetString("JobManager_InvalidState_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job system is in invalid state. This indicates a miscommunication or internal error has happened. The current session may not be recovered, so it is advised to restart the application..
        /// </summary>
        public static string JobManager_InvalidState_Text {
            get {
                return ResourceManager.GetString("JobManager_InvalidState_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition was cancelled.
        /// </summary>
        public static string JobManager_MB_Acq_Cancelled_Header {
            get {
                return ResourceManager.GetString("JobManager_MB_Acq_Cancelled_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition has been terminated by the user!.
        /// </summary>
        public static string JobManager_MB_Acq_Cancelled_Text {
            get {
                return ResourceManager.GetString("JobManager_MB_Acq_Cancelled_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition cycle failed!.
        /// </summary>
        public static string JobManager_MB_Failed_Header {
            get {
                return ResourceManager.GetString("JobManager_MB_Failed_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition cycle was interrupted with the following error: 
        ///{0}.
        /// </summary>
        public static string JobManager_MB_Failed_Text {
            get {
                return ResourceManager.GetString("JobManager_MB_Failed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition cycle finished.
        /// </summary>
        public static string JobManager_MB_Finished_Header {
            get {
                return ResourceManager.GetString("JobManager_MB_Finished_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquired {0}..
        /// </summary>
        public static string JobManager_MB_Finished_Text {
            get {
                return ResourceManager.GetString("JobManager_MB_Finished_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photometry cycle should not be run when the instrument is in &quot;Polarimeter&quot; regime. Make sure the instrument is switched to the &quot;Photometer&quot; mode..
        /// </summary>
        public static string JobManager_NotPhotometry {
            get {
                return ResourceManager.GetString("JobManager_NotPhotometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polarimetry cycle requires connected step motors and instrument in &quot;Polarimeter&quot; regime. Make sure motors are connected and instrument mode is switched to &quot;Polarimeter&quot;..
        /// </summary>
        public static string JobManager_NotPolarimetry {
            get {
                return ResourceManager.GetString("JobManager_NotPolarimetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take calibrations?.
        /// </summary>
        public static string JobManager_TakeCalibrations_Header {
            get {
                return ResourceManager.GetString("JobManager_TakeCalibrations_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrations are missing because either calibration or acquisition were interrupted, or dipol parameters has changed since last calibration.
        ///Do you want to take new calibration frames?.
        /// </summary>
        public static string JobManager_TakeCalibrations_Text {
            get {
                return ResourceManager.GetString("JobManager_TakeCalibrations_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrations are required.
        /// </summary>
        public static string JobManager_TakeCalibrationsFirstTime_Header {
            get {
                return ResourceManager.GetString("JobManager_TakeCalibrationsFirstTime_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target `{0}` is observed for the first time and there are no calibrations. Do you want to take calibrations needed for correct data reduction?.
        /// </summary>
        public static string JobManager_TakeCalibrationsFirstTime_Text {
            get {
                return ResourceManager.GetString("JobManager_TakeCalibrationsFirstTime_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string JobSetting_Modify {
            get {
                return ResourceManager.GetString("JobSetting_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bias file.
        /// </summary>
        public static string JobSettings_BiasFile {
            get {
                return ResourceManager.GetString("JobSettings_BiasFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CycleType:.
        /// </summary>
        public static string JobSettings_CycleType {
            get {
                return ResourceManager.GetString("JobSettings_CycleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark file.
        /// </summary>
        public static string JobSettings_DarkFile {
            get {
                return ResourceManager.GetString("JobSettings_DarkFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object description:.
        /// </summary>
        public static string JobSettings_Description {
            get {
                return ResourceManager.GetString("JobSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose file with acquisition settings.
        /// </summary>
        public static string JobSettings_Dialog_Acquisition {
            get {
                return ResourceManager.GetString("JobSettings_Dialog_Acquisition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose file with job settings.
        /// </summary>
        public static string JobSettings_Dialog_Job {
            get {
                return ResourceManager.GetString("JobSettings_Dialog_Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load observation target.
        /// </summary>
        public static string JobSettings_Dialog_Load {
            get {
                return ResourceManager.GetString("JobSettings_Dialog_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current observation target.
        /// </summary>
        public static string JobSettings_Dialog_Save {
            get {
                return ResourceManager.GetString("JobSettings_Dialog_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp. times (s):.
        /// </summary>
        public static string JobSettings_ExposureTime {
            get {
                return ResourceManager.GetString("JobSettings_ExposureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job file:.
        /// </summary>
        public static string JobSettings_JobFile {
            get {
                return ResourceManager.GetString("JobSettings_JobFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of cycles.
        /// </summary>
        public static string JobSettings_N_repeats {
            get {
                return ResourceManager.GetString("JobSettings_N_repeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual exposure times:.
        /// </summary>
        public static string JobSettings_PerCameraExposures {
            get {
                return ResourceManager.GetString("JobSettings_PerCameraExposures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared settings:.
        /// </summary>
        public static string JobSettings_SettingsBlock {
            get {
                return ResourceManager.GetString("JobSettings_SettingsBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acq. file.
        /// </summary>
        public static string JobSettings_SettingsFile {
            get {
                return ResourceManager.GetString("JobSettings_SettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star name:.
        /// </summary>
        public static string JobSettings_TargetName {
            get {
                return ResourceManager.GetString("JobSettings_TargetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up job.
        /// </summary>
        public static string JobSettings_WindowName {
            get {
                return ResourceManager.GetString("JobSettings_WindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Manager.
        /// </summary>
        public static string MainWindow_CameraManager {
            get {
                return ResourceManager.GetString("MainWindow_CameraManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to remote services....
        /// </summary>
        public static string MainWindow_ConnectingToRemoteLocations {
            get {
                return ResourceManager.GetString("MainWindow_ConnectingToRemoteLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MainWindow_MB_FailedToAddCamera_Caption {
            get {
                return ResourceManager.GetString("MainWindow_MB_FailedToAddCamera_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect camera {0}. Please, try again..
        /// </summary>
        public static string MainWindow_MB_FailedToAddCamera_Message {
            get {
                return ResourceManager.GetString("MainWindow_MB_FailedToAddCamera_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainWindow_MB_PolarimeterMotorFailure_Caption {
            get {
                return ResourceManager.GetString("MainWindow_MB_PolarimeterMotorFailure_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A failure is detected in either hardware or software. Step motor cannot be connected. Make sure it is powered on and accessible, restart the program and try again..
        /// </summary>
        public static string MainWindow_MB_PolarimeterMotorFailure_Text {
            get {
                return ResourceManager.GetString("MainWindow_MB_PolarimeterMotorFailure_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step motor is unavailable.
        /// </summary>
        public static string MainWindow_MB_PolarimeterMotorNotFound_Caption {
            get {
                return ResourceManager.GetString("MainWindow_MB_PolarimeterMotorNotFound_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step motor on preferred port {0} is not found. Make sure the polarimeter is connected and turned on. If you want to rescan, press [Yes]..
        /// </summary>
        public static string MainWindow_MB_PolarimeterMotorNotFound_Text {
            get {
                return ResourceManager.GetString("MainWindow_MB_PolarimeterMotorNotFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step motor is OK.
        /// </summary>
        public static string MainWindow_MB_PolarimeterMotorOK_Caption {
            get {
                return ResourceManager.GetString("MainWindow_MB_PolarimeterMotorOK_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step motor on port {0} at address {1:00} is healthy and responding.
        ///Position is {2}..
        /// </summary>
        public static string MainWindow_MB_PolarimeterMotorOK_Text {
            get {
                return ResourceManager.GetString("MainWindow_MB_PolarimeterMotorOK_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step motor on port {0} at address {1:00} is healthy and responding.
        ///Position is {2}.
        ///Click &quot;Yes&quot; if you would like to re-calibrate its position..
        /// </summary>
        public static string MainWindow_MB_PolarimeterMotorOK_Text_2 {
            get {
                return ResourceManager.GetString("MainWindow_MB_PolarimeterMotorOK_Text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot exit application while acquisition is in progress..
        /// </summary>
        public static string MainWindow_Notify_Closing_Acquisition {
            get {
                return ResourceManager.GetString("MainWindow_Notify_Closing_Acquisition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing &apos;Dipol-UF&apos;.
        /// </summary>
        public static string MainWindow_Notify_Closing_Caption {
            get {
                return ResourceManager.GetString("MainWindow_Notify_Closing_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the window and exit the application?.
        /// </summary>
        public static string MainWindow_Notify_Closing_Message {
            get {
                return ResourceManager.GetString("MainWindow_Notify_Closing_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one camera has temperature below 0 degrees. It is recommended to wait until all cameras are heated up. Are you sure you want ot exit?.
        /// </summary>
        public static string MainWindow_Notify_Closing_NegativeTemp {
            get {
                return ResourceManager.GetString("MainWindow_Notify_Closing_NegativeTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot exit application when the intrument is not in polarimetric regime! Please switch to &apos;Polariemtry&apos; and try again..
        /// </summary>
        public static string MainWindow_Notify_Closing_NotPolarimeter {
            get {
                return ResourceManager.GetString("MainWindow_Notify_Closing_NotPolarimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot exit application while observation regime is being switched!.
        /// </summary>
        public static string MainWindow_Notify_Closing_RegimeSwitching {
            get {
                return ResourceManager.GetString("MainWindow_Notify_Closing_RegimeSwitching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photometer.
        /// </summary>
        public static string MainWindow_Photometer {
            get {
                return ResourceManager.GetString("MainWindow_Photometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polarimeter.
        /// </summary>
        public static string MainWindow_Polariemter {
            get {
                return ResourceManager.GetString("MainWindow_Polariemter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No motor.
        /// </summary>
        public static string MainWindow_PolarimeterButton_None {
            get {
                return ResourceManager.GetString("MainWindow_PolarimeterButton_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor OK.
        /// </summary>
        public static string MainWindow_PolarimeterButton_Present {
            get {
                return ResourceManager.GetString("MainWindow_PolarimeterButton_Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching from {0} to {1}. Please wait..
        /// </summary>
        public static string MainWindow_Regime_Switching_Text {
            get {
                return ResourceManager.GetString("MainWindow_Regime_Switching_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching instrument regime.
        /// </summary>
        public static string MainWindow_Regime_Swtitching_Title {
            get {
                return ResourceManager.GetString("MainWindow_Regime_Swtitching_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {0} out of {1}.
        /// </summary>
        public static string MainWindow_RemoteConnection_ClientCount {
            get {
                return ResourceManager.GetString("MainWindow_RemoteConnection_ClientCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No retractor.
        /// </summary>
        public static string MainWindow_RetractorButton_None {
            get {
                return ResourceManager.GetString("MainWindow_RetractorButton_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retractor OK.
        /// </summary>
        public static string MainWindow_RetractorButton_Present {
            get {
                return ResourceManager.GetString("MainWindow_RetractorButton_Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} more errors that were not shown..
        /// </summary>
        public static string MB_MoreLeft {
            get {
                return ResourceManager.GetString("MB_MoreLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Menu_MainWindow_CameraProperties {
            get {
                return ResourceManager.GetString("Menu_MainWindow_CameraProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{0, {0:F0} }}/{{1, {0:F0} }}.
        /// </summary>
        public static string ProgressBar_DisplayCountFormatString {
            get {
                return ResourceManager.GetString("ProgressBar_DisplayCountFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F0}%.
        /// </summary>
        public static string ProgressBar_DisplayPercentString {
            get {
                return ResourceManager.GetString("ProgressBar_DisplayPercentString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{0, {0:F0} }} in ({{1, {0:F0} }}, {{2, {0:F0} }}).
        /// </summary>
        public static string ProgressBar_DisplayRangeFormatString {
            get {
                return ResourceManager.GetString("ProgressBar_DisplayRangeFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProgressBar_IndeterminateString {
            get {
                return ResourceManager.GetString("ProgressBar_IndeterminateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProgressBar_IsInvalidString {
            get {
                return ResourceManager.GetString("ProgressBar_IsInvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Properties_Localization_MainWindow_Notify_Closing_NotPolarimeter {
            get {
                return ResourceManager.GetString("Properties.Localization.MainWindow_Notify_Closing_NotPolarimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host not found or unreachable.
        /// </summary>
        public static string RemoteConnection_UnreachableHostTitle {
            get {
                return ResourceManager.GetString("RemoteConnection_UnreachableHostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure time:.
        /// </summary>
        public static string Settings_ExposureTime {
            get {
                return ResourceManager.GetString("Settings_ExposureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:f0} pix.
        /// </summary>
        public static string Slider_PixelToolTipFormat {
            get {
                return ResourceManager.GetString("Slider_PixelToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFS is not configured.
        /// </summary>
        public static string StepMotor_MissingRFSSwitchStatus_Header {
            get {
                return ResourceManager.GetString("StepMotor_MissingRFSSwitchStatus_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference search success status is not set in the configuration file. Make sure &quot;{0}&quot; is set to eitehr `1` or `0` depending on the model of the motor. Until it is fixed, RFS is unreliable..
        /// </summary>
        public static string StepMotor_MissingRFSSwitchStatus_Message {
            get {
                return ResourceManager.GetString("StepMotor_MissingRFSSwitchStatus_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:g7}.
        /// </summary>
        public static string StringFormat_Float_DipolImagePresenter_Statistics {
            get {
                return ResourceManager.GetString("StringFormat_Float_DipolImagePresenter_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value is illegal.
        /// </summary>
        public static string Validation_CannotBeDefault {
            get {
                return ResourceManager.GetString("Validation_CannotBeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input format.
        /// </summary>
        public static string Validation_CannotBeParsed {
            get {
                return ResourceManager.GetString("Validation_CannotBeParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only numeric values are permitted.
        /// </summary>
        public static string Validation_OnlyNumbersAllowed {
            get {
                return ResourceManager.GetString("Validation_OnlyNumbersAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only letters, digits, +. -. _ symbols are allowed.
        /// </summary>
        public static string Validation_ShouldBeSimpleString {
            get {
                return ResourceManager.GetString("Validation_ShouldBeSimpleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be greater than {0}.
        /// </summary>
        public static string Validation_ValueCannotBeGreaterThan {
            get {
                return ResourceManager.GetString("Validation_ValueCannotBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be less than {0}.
        /// </summary>
        public static string Validation_ValueCannotBeLessThan {
            get {
                return ResourceManager.GetString("Validation_ValueCannotBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input contains disallowed symbols{0}.
        /// </summary>
        public static string Validation_ValueMatchesRegex {
            get {
                return ResourceManager.GetString("Validation_ValueMatchesRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be outside of the [{0}, {1}] range.
        /// </summary>
        public static string Validation_ValueShouldFallWithinRange {
            get {
                return ResourceManager.GetString("Validation_ValueShouldFallWithinRange", resourceCulture);
            }
        }
    }
}
