//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIPOL_UF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DIPOL_UF.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperture settings.
        /// </summary>
        public static string DipolImagePresenter_ApertureControlGroup {
            get {
                return ResourceManager.GetString("DipolImagePresenter_ApertureControlGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gap.
        /// </summary>
        public static string DipolImagePresenter_Geometry_Gap {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Geometry_Gap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line thickness.
        /// </summary>
        public static string DipolImagePresenter_Geometry_Thickness {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Geometry_Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string DipolImagePresenter_Geometry_Type {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Geometry_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulus.
        /// </summary>
        public static string DipolImagePresenter_Statistics_Annulus {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_Annulus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperture.
        /// </summary>
        public static string DipolImagePresenter_Statistics_Aperture {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_Aperture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string DipolImagePresenter_Statistics_Average {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center pixel.
        /// </summary>
        public static string DipolImagePresenter_Statistics_CenterPixel {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_CenterPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string DipolImagePresenter_Statistics_CenterPosition {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_CenterPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string DipolImagePresenter_Statistics_CenterValue {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_CenterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        public static string DipolImagePresenter_Statistics_Intensity {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_Intensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string DipolImagePresenter_Statistics_Maximum {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median.
        /// </summary>
        public static string DipolImagePresenter_Statistics_Median {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_Median", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string DipolImagePresenter_Statistics_Minimum {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNR.
        /// </summary>
        public static string DipolImagePresenter_Statistics_SignalToNoise {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_SignalToNoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD.
        /// </summary>
        public static string DipolImagePresenter_Statistics_StandardDev {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_StandardDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string General_Color {
            get {
                return ResourceManager.GetString("General_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:g7}.
        /// </summary>
        public static string StringFormat_Float_DipolImagePresenter_Statistics {
            get {
                return ResourceManager.GetString("StringFormat_Float_DipolImagePresenter_Statistics", resourceCulture);
            }
        }
    }
}
