//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIPOL_UF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DIPOL_UF.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycles.
        /// </summary>
        public static string AcquisitionSettings_Cycles {
            get {
                return ResourceManager.GetString("AcquisitionSettings_Cycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size.
        /// </summary>
        public static string AcquisitionSettings_ImageSize {
            get {
                return ResourceManager.GetString("AcquisitionSettings_ImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string AcquisitionSettings_Settings {
            get {
                return ResourceManager.GetString("AcquisitionSettings_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up acquisition process.
        /// </summary>
        public static string AcquisitionSettings_WindowName {
            get {
                return ResourceManager.GetString("AcquisitionSettings_WindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dipol-UF.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Cameras.
        /// </summary>
        public static string AvailableCameras {
            get {
                return ResourceManager.GetString("AvailableCameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquired local camera {0}..
        /// </summary>
        public static string AvailableCameras_AcquiredLocalCamera {
            get {
                return ResourceManager.GetString("AvailableCameras_AcquiredLocalCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquired remote camera {0}..
        /// </summary>
        public static string AvailableCameras_AcquiredRemoteCamera {
            get {
                return ResourceManager.GetString("AvailableCameras_AcquiredRemoteCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera resource is unavailable..
        /// </summary>
        public static string AvailableCameras_CameraIsUnavailable {
            get {
                return ResourceManager.GetString("AvailableCameras_CameraIsUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking connections....
        /// </summary>
        public static string AvailableCameras_CheckingConnection_BarTitle {
            get {
                return ResourceManager.GetString("AvailableCameras_CheckingConnection_BarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        public static string AvailableCameras_Found {
            get {
                return ResourceManager.GetString("AvailableCameras_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cameras available. Check connections and try again..
        /// </summary>
        public static string AvailableCameras_NoNewCameras {
            get {
                return ResourceManager.GetString("AvailableCameras_NoNewCameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string CameraProperties_Alias {
            get {
                return ResourceManager.GetString("CameraProperties_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Model.
        /// </summary>
        public static string CameraProperties_CamModel {
            get {
                return ResourceManager.GetString("CameraProperties_CamModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Version.
        /// </summary>
        public static string CameraProperties_HardwareVers {
            get {
                return ResourceManager.GetString("CameraProperties_HardwareVers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string CameraProperties_Property {
            get {
                return ResourceManager.GetString("CameraProperties_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string CameraProperties_SerialNumber {
            get {
                return ResourceManager.GetString("CameraProperties_SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Version.
        /// </summary>
        public static string CameraProperties_SoftwareVers {
            get {
                return ResourceManager.GetString("CameraProperties_SoftwareVers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string CameraProperties_UnknownValue {
            get {
                return ResourceManager.GetString("CameraProperties_UnknownValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string CameraProperties_Value {
            get {
                return ResourceManager.GetString("CameraProperties_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition.
        /// </summary>
        public static string CameraTab_Acquisition {
            get {
                return ResourceManager.GetString("CameraTab_Acquisition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acq. Settings.
        /// </summary>
        public static string CameraTab_AcquisitionSettings {
            get {
                return ResourceManager.GetString("CameraTab_AcquisitionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autosave.
        /// </summary>
        public static string CameraTab_Autosave_Checkbox {
            get {
                return ResourceManager.GetString("CameraTab_Autosave_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooler.
        /// </summary>
        public static string CameraTab_Cooler {
            get {
                return ResourceManager.GetString("CameraTab_Cooler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start cooling.
        /// </summary>
        public static string CameraTab_Cooler_Start {
            get {
                return ResourceManager.GetString("CameraTab_Cooler_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop cooling.
        /// </summary>
        public static string CameraTab_Cooler_Stop {
            get {
                return ResourceManager.GetString("CameraTab_Cooler_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan.
        /// </summary>
        public static string CameraTab_Fan {
            get {
                return ResourceManager.GetString("CameraTab_Fan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Imaging.
        /// </summary>
        public static string CameraTab_Imaging_Start {
            get {
                return ResourceManager.GetString("CameraTab_Imaging_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Imaging.
        /// </summary>
        public static string CameraTab_Imaging_Stop {
            get {
                return ResourceManager.GetString("CameraTab_Imaging_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        public static string CameraTab_Shutter_External {
            get {
                return ResourceManager.GetString("CameraTab_Shutter_External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        public static string CameraTab_Shutter_Internal {
            get {
                return ResourceManager.GetString("CameraTab_Shutter_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acc.
        /// </summary>
        public static string CameraTab_Timing_AccumulationCycle {
            get {
                return ResourceManager.GetString("CameraTab_Timing_AccumulationCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp.
        /// </summary>
        public static string CameraTab_Timing_Exposure {
            get {
                return ResourceManager.GetString("CameraTab_Timing_Exposure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kin.
        /// </summary>
        public static string CameraTab_Timing_KineticCycle {
            get {
                return ResourceManager.GetString("CameraTab_Timing_KineticCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperture settings.
        /// </summary>
        public static string DipolImagePresenter_ApertureControlGroup {
            get {
                return ResourceManager.GetString("DipolImagePresenter_ApertureControlGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gap.
        /// </summary>
        public static string DipolImagePresenter_Geometry_Gap {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Geometry_Gap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line thickness.
        /// </summary>
        public static string DipolImagePresenter_Geometry_Thickness {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Geometry_Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string DipolImagePresenter_Geometry_Type {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Geometry_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulus.
        /// </summary>
        public static string DipolImagePresenter_Statistics_Annulus {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_Annulus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperture.
        /// </summary>
        public static string DipolImagePresenter_Statistics_Aperture {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_Aperture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string DipolImagePresenter_Statistics_Average {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center pixel.
        /// </summary>
        public static string DipolImagePresenter_Statistics_CenterPixel {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_CenterPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string DipolImagePresenter_Statistics_CenterPosition {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_CenterPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string DipolImagePresenter_Statistics_CenterValue {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_CenterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensity.
        /// </summary>
        public static string DipolImagePresenter_Statistics_Intensity {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_Intensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string DipolImagePresenter_Statistics_Maximum {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median.
        /// </summary>
        public static string DipolImagePresenter_Statistics_Median {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_Median", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string DipolImagePresenter_Statistics_Minimum {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNR.
        /// </summary>
        public static string DipolImagePresenter_Statistics_SignalToNoise {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_SignalToNoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD.
        /// </summary>
        public static string DipolImagePresenter_Statistics_StandardDev {
            get {
                return ResourceManager.GetString("DipolImagePresenter_Statistics_StandardDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string General_Abort {
            get {
                return ResourceManager.GetString("General_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string General_Cancel {
            get {
                return ResourceManager.GetString("General_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string General_Color {
            get {
                return ResourceManager.GetString("General_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string General_Connect {
            get {
                return ResourceManager.GetString("General_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect All.
        /// </summary>
        public static string General_ConnectAll {
            get {
                return ResourceManager.GetString("General_ConnectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string General_Disconnect {
            get {
                return ResourceManager.GetString("General_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string General_FanMode_Full {
            get {
                return ResourceManager.GetString("General_FanMode_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string General_FanMode_Low {
            get {
                return ResourceManager.GetString("General_FanMode_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string General_FanMode_Off {
            get {
                return ResourceManager.GetString("General_FanMode_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:+0.00;-0.00;0.00}.
        /// </summary>
        public static string General_FloatTempFormat {
            get {
                return ResourceManager.GetString("General_FloatTempFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} is invalid..
        /// </summary>
        public static string General_InvalidArgument {
            get {
                return ResourceManager.GetString("General_InvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string General_Load {
            get {
                return ResourceManager.GetString("General_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string General_LocalHostName {
            get {
                return ResourceManager.GetString("General_LocalHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation [{0}] is not supported..
        /// </summary>
        public static string General_OperationNotSupported {
            get {
                return ResourceManager.GetString("General_OperationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string General_Save {
            get {
                return ResourceManager.GetString("General_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has happened. This is indicates a likely unrecoverable error in the software. Consider reporting it..
        /// </summary>
        public static string General_ShouldNotHappen {
            get {
                return ResourceManager.GetString("General_ShouldNotHappen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string General_Submit {
            get {
                return ResourceManager.GetString("General_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F2.
        /// </summary>
        public static string General_TemperatureFloatFormat {
            get {
                return ResourceManager.GetString("General_TemperatureFloatFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drifting.
        /// </summary>
        public static string General_TemperatureStatus_Drift {
            get {
                return ResourceManager.GetString("General_TemperatureStatus_Drift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not reached.
        /// </summary>
        public static string General_TemperatureStatus_NotReached {
            get {
                return ResourceManager.GetString("General_TemperatureStatus_NotReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not stabilized.
        /// </summary>
        public static string General_TemperatureStatus_NotStabilized {
            get {
                return ResourceManager.GetString("General_TemperatureStatus_NotStabilized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string General_TemperatureStatus_Off {
            get {
                return ResourceManager.GetString("General_TemperatureStatus_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stabilized.
        /// </summary>
        public static string General_TemperatureStatus_Stabilized {
            get {
                return ResourceManager.GetString("General_TemperatureStatus_Stabilized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Manager.
        /// </summary>
        public static string MainWindow_CameraManager {
            get {
                return ResourceManager.GetString("MainWindow_CameraManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MainWindow_MB_FailedToAddCamera_Caption {
            get {
                return ResourceManager.GetString("MainWindow_MB_FailedToAddCamera_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect camera {0}. Please, try again..
        /// </summary>
        public static string MainWindow_MB_FailedToAddCamera_Message {
            get {
                return ResourceManager.GetString("MainWindow_MB_FailedToAddCamera_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Menu_MainWindow_CameraProperties {
            get {
                return ResourceManager.GetString("Menu_MainWindow_CameraProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{0, {0:F0} }}/{{1, {0:F0} }}.
        /// </summary>
        public static string ProgressBar_DisplayCountFormatString {
            get {
                return ResourceManager.GetString("ProgressBar_DisplayCountFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F0}%.
        /// </summary>
        public static string ProgressBar_DisplayPercentString {
            get {
                return ResourceManager.GetString("ProgressBar_DisplayPercentString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{0, {0:F0} }} in ({{1, {0:F0} }}, {{2, {0:F0} }}).
        /// </summary>
        public static string ProgressBar_DisplayRangeFormatString {
            get {
                return ResourceManager.GetString("ProgressBar_DisplayRangeFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProgressBar_IndeterminateString {
            get {
                return ResourceManager.GetString("ProgressBar_IndeterminateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProgressBar_IsInvalidString {
            get {
                return ResourceManager.GetString("ProgressBar_IsInvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host not found or unreachable.
        /// </summary>
        public static string RemoteConnection_UnreachableHostTitle {
            get {
                return ResourceManager.GetString("RemoteConnection_UnreachableHostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:f0} pix.
        /// </summary>
        public static string Slider_PixelToolTipFormat {
            get {
                return ResourceManager.GetString("Slider_PixelToolTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:g7}.
        /// </summary>
        public static string StringFormat_Float_DipolImagePresenter_Statistics {
            get {
                return ResourceManager.GetString("StringFormat_Float_DipolImagePresenter_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value is illegal.
        /// </summary>
        public static string Validation_CannotBeDefault {
            get {
                return ResourceManager.GetString("Validation_CannotBeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be greater than {0}.
        /// </summary>
        public static string Validation_ValueCannotBeGreaterThan {
            get {
                return ResourceManager.GetString("Validation_ValueCannotBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be less than {0}.
        /// </summary>
        public static string Validation_ValueCannotBeLessThan {
            get {
                return ResourceManager.GetString("Validation_ValueCannotBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input contains disallowed symbols{0}.
        /// </summary>
        public static string Validation_ValueMatchesRegex {
            get {
                return ResourceManager.GetString("Validation_ValueMatchesRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be outside of the [{0}, {1}] range.
        /// </summary>
        public static string Validation_ValueShouldFallWithinRange {
            get {
                return ResourceManager.GetString("Validation_ValueShouldFallWithinRange", resourceCulture);
            }
        }
    }
}
