name: Test cross-platform libs (Lin)

on:
  push:
    branches: 
      - main
      - master
      - staging
    paths:
      - '**/*cs'
      - '**/*csproj'
      - '**/*sln'
      - '**/*xaml'
      - '**/*resx'
      - '**/*config'
      - '**/*yml'
  pull_request:
    branches: 
      - main
      - master
      - staging
    paths:
      - '**/*cs'
      - '**/*csproj'
      - '**/*sln'
      - '**/*xaml'
      - '**/*resx'
      - '**/*config'
      - '**/*yml'
  workflow_dispatch:

jobs:
  test_resources:
    runs-on: 'ubuntu-latest'
    name: 'ubuntu-latest'

    defaults:
      run:
        shell: pwsh
    env: 
      GITHUB_NUGET_RO: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download test data
        run: |
          New-Item -Type Directory -ErrorAction SilentlyContinue tests/TestData
          Invoke-WebRequest https://fits.gsfc.nasa.gov/samples/UITfuv2582gc.fits -OutFile tests/TestData/UITfuv2582gc.fits
          Invoke-WebRequest https://fits.gsfc.nasa.gov/nrao_data/tests/nost_headers/bitpix13.fits -OutFile tests/TestData/unsupp_bitpix.fits

      - name: Run cross-platform tests
        run: |
          dotnet test tests -c Release
 
          


