name: Build executables

on:
  push:
    branches: 
      - main
      - master
      - staging
      - 'windows-ci'
    paths:
      - '**/*cs'
      - '**/*csproj'
      - '**/*sln'
      - '**/*xaml'
      - '**/*resx'
      - '**/*config'
      - '**/*yml'
  pull_request:
    branches: 
      - main
      - master
      - staging
    paths:
      - '**/*cs'
      - '**/*csproj'
      - '**/*sln'
      - '**/*xaml'
      - '**/*resx'
      - '**/*config'
      - '**/*yml'
  workflow_dispatch:

jobs:
  build_exe:

    runs-on: 'windows-latest'
    name: Building Dipol-UF.exe & Host.exe

    defaults:
      run:
        shell: pwsh
    env: 
      GITHUB_NUGET_RO: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Get deps
        run: |
          iex $env:DIPOL_PRIVATE_DEPS_PWSH
        env:
          DIPOL_PRIVATE_DEPS_PWSH: ${{secrets.DIPOL_PRIVATE_DEPS_PWSH}}
      
      - name: Restore Host
        run: |
           MSBuild.exe .\Host\Host.csproj -t:restore

      - name: Build Host x86
        run: |
           MSBuild.exe .\Host\Host.csproj -p:Configuration=Release -p:Platform=x86

      - name: Build Host x64
        run: |
           MSBuild.exe .\Host\Host.csproj -p:Configuration=Release -p:Platform=x64

          
      - name: Restore Dipol-UF
        run: |
           MSBuild.exe .\Dipol-UF\Dipol-UF.csproj -t:restore

      - name: Build Dipol-UF x86
        run: |
           MSBuild.exe .\Dipol-UF\Dipol-UF.csproj -p:Configuration=Release -p:Platform=x86

      - name: Build Dipol-UF x64
        run: |
           MSBuild.exe .\Dipol-UF\Dipol-UF.csproj -p:Configuration=Release -p:Platform=x64
