name: Build executables

on:
  push:
    branches: 
      - main
      - master
      - staging
    paths:
      - '**/*cs'
      - '**/*csproj'
      - '**/*sln'
      - '**/*xaml'
      - '**/*resx'
      - '**/*config'
      - '**/win-ci.yml'
      - '.gitignore'
  # pull_request:
  #   branches: 
  #     - main
  #     - master
  #     - staging
  #   paths:
  #     - '**/*cs'
  #     - '**/*csproj'
  #     - '**/*sln'
  #     - '**/*xaml'
  #     - '**/*resx'
  #     - '**/*config'
  #     - '**/win-ci.yml'
  #     - '.gitignore'
  workflow_dispatch:

jobs:
  build_exe:

    runs-on: 'windows-latest'
    name: Building Dipol-UF.exe & Host.exe

    defaults:
      run:
        shell: pwsh
    env: 
      GITHUB_NUGET_RO: ${{ secrets.NUGET_RO }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore Host
        run: |
           MSBuild.exe .\src\Host\Host.csproj -t:restore

      - name: Build Host x86
        run: |
           MSBuild.exe .\src\Host\Host.csproj -p:Configuration=Release -p:Platform=x86

      - name: Build Host x64
        run: |
           MSBuild.exe .\src\Host\Host.csproj -p:Configuration=Release -p:Platform=x64

          
      - name: Restore Dipol-UF
        run: |
           MSBuild.exe .\src\Dipol-UF\Dipol-UF.csproj -t:restore

      - name: Build Dipol-UF x86
        run: |
           MSBuild.exe .\src\Dipol-UF\Dipol-UF.csproj -p:Configuration=Release -p:Platform=x86

      - name: Build Dipol-UF x64
        run: |
           MSBuild.exe .\src\Dipol-UF\Dipol-UF.csproj -p:Configuration=Release -p:Platform=x64
