name: Build executables

on:
  push:
    branches: 
      - main
      - master
      - staging
      - 'windows-ci'
    paths:
      - '**/*cs'
      - '**/*csproj'
      - '**/*sln'
      - '**/*xaml'
      - '**/*resx'
      - '**/*config'
      - '**/*yml'
  pull_request:
    branches: 
      - main
      - master
      - staging
    paths:
      - '**/*cs'
      - '**/*csproj'
      - '**/*sln'
      - '**/*xaml'
      - '**/*resx'
      - '**/*config'
      - '**/*yml'
  workflow_dispatch:

jobs:
  build_exe:

    runs-on: 'windows-latest'
    name: Building Dipol-UF.exe & Host.exe

    defaults:
      run:
        shell: pwsh
    env: 
      GITHUB_NUGET_RO: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Get deps
        run: |
          iex $env:DIPOL_PRIVATE_DEPS_PWSH
        env:
          DIPOL_PRIVATE_DEPS_PWSH: ${{secrets.DIPOL_PRIVATE_DEPS_PWSH}}
      
      - name: Build Host
        run: |
           MSBuild.exe .\Host\Host.csproj -t:restore
           MSBuild.exe .\Host\Host.csproj -p:Configuration=Release -p:Platform=x86
           MSBuild.exe .\Host\Host.csproj -p:Configuration=Release -p:Platform=x64

          


